"""added field to application

Revision ID: 7ed2f720cbd4
Revises: bcc5f2f8357f
Create Date: 2025-10-29 13:05:38.717922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed2f720cbd4'
down_revision = 'bcc5f2f8357f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recruiter_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('recruiter_email', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('recruiter_email')
        batch_op.drop_column('recruiter_name')
        batch_op.drop_column('priority_level')

    # ### end Alembic commands ###
