"""added Applications table

Revision ID: 80e787f9c069
Revises: 2dee9d689c4a
Create Date: 2025-10-29 12:33:25.301237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e787f9c069'
down_revision = '2dee9d689c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=80), nullable=False),
    sa.Column('job_title', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('date_applied', sa.DateTime(), nullable=False),
    sa.Column('current_status', sa.Enum('APPLIED', 'PHONE_SCREEN_SCHEDULED', 'PHONE_SCREEN_COMPLETED', 'TECHNICAL_INTERVIEW_SCHEDULED', 'TECHNICAL_INTERVIEW_COMPLETED', 'FINAL_ROUND', 'OFFER_RECEIVED', 'REJECTED', 'ACCEPTED', 'WITHDRAWN', name='statusenum'), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.Text(), nullable=False),
    sa.Column('years_of_experience', sa.Float(), nullable=False),
    sa.Column('posted_salary', sa.String(length=80), nullable=False),
    sa.Column('predicted_salary', sa.String(length=80), nullable=False),
    sa.Column('actual_offer', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
