"""made posted_salary and required_skill nullable

Revision ID: bcc5f2f8357f
Revises: fe8e65547d8a
Create Date: 2025-10-29 13:02:35.148887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcc5f2f8357f'
down_revision = 'fe8e65547d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('required_skills',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('posted_salary',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('posted_salary',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('required_skills',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
