"""changes to applications table

Revision ID: fe8e65547d8a
Revises: 05a9d95f74fa
Create Date: 2025-10-29 12:55:03.491749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe8e65547d8a'
down_revision = '05a9d95f74fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('predicted_salary',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('actual_offer',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('actual_offer',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('predicted_salary',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
